### ISSUE TITLE
Fix text effects not rendering properly

### ISSUE THREAD

**Issue by Slips-PC** [hexereii/BerryHUD#3]
On some maps (namely tr_walkway in my case), text effects i.e the hover text that shows when you mouse over a button in tr_walkway just don't render at all for me. I don't know how this could be fixed (i know very little about tf2 hud customization) but it's very annoying, so if you can take a look that'd be much appreciated.

**Comment by hexereii** [comment]
Will do, also will update on here when it is fixed o7

**Comment by hexereii** [comment]
> On some maps (namely tr_walkway in my case), text effects i.e the hover text that shows when you mouse over a button in tr_walkway just don't render at all for me. I don't know how this could be fixed (i know very little about tf2 hud customization) but it's very annoying, so if you can take a look that'd be much appreciated.

Fixed! Sorry for delay, it was a very obscure issue. Let me know if you need any help! discord: heks#2740

**Comment by Slips-PC** [comment]
Looks good, thanks!
